version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.4.0
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: aws-sdk-ssm
    versions:
    - 1.103.0
    - 1.104.0
    - 1.105.0
    - 1.106.0
    - 1.107.0
  - dependency-name: aws-sdk-lambda
    versions:
    - 1.57.0
    - 1.58.0
    - 1.59.0
    - 1.60.0
    - 1.61.0
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: honeybadger
    versions:
    - 4.7.2
    - 4.7.3
  - dependency-name: aws-sdk-dynamodb
    versions:
    - 1.58.0
    - 1.59.0
